#lang sicp

(define (make-account balance password)
  (define password-incorrect 0)
  (define call-the-cops "Password guessed incorrectly seven times, cops have been called")
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p password)
        (begin (set! password-incorrect 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request: MAKE-ACCOUNT" m))))
        (lambda (i) (begin (set! password-incorrect (+ 1 password-incorrect))
                           (if (eq? password-incorrect 7)
                               call-the-cops
                               "Incorrect password")))))
  dispatch)